version: '3.4'

networks:
  cors_dev:
    external: true

services:
  db:
      image: mysql:8
      container_name: cors-adminer
      networks:
        - cors_dev
      working_dir: /application
      volumes:
        - adminer-database:/var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=ROOT
        - MYSQL_DATABASE=pimcore
        - MYSQL_USER=pimcore
        - MYSQL_PASSWORD=pimcore

  nginx:
    image: nginx:stable-alpine
    container_name: adminer_database-nginx
    labels:
      - traefik.enable=true
      - traefik.http.routers.adminer_database.rule=Host(`cors-adminer.localhost`)
      - traefik.http.routers.adminer_database.entrypoints=cors_dev
      - traefik.http.routers.adminer_database.tls=true
      - traefik.http.services.adminer_database.loadbalancer.server.port=80
      - traefik.docker.network=cors_dev
    networks:
      - cors_dev
    volumes:
      - ./:/var/www/html:ro
      - ./.docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
      - php-debug

  php:
    image: ghcr.io/cors-gmbh/pimcore-docker/php-fpm:8.3-alpine3.21-7.0-LATEST
    container_name: php-cors-adminer
    command: 'php-fpm'
    entrypoint: docker-php-entrypoint
    networks:
      - cors_dev
    depends_on:
      - db
    volumes:
      - ./:/var/www/html:cached
      - ./.docker/php.ini:/usr/local/etc/php/conf.d/docker-php-ext-additional.ini:ro
    environment:
      - COMPOSER_AUTH=${COMPOSER_AUTH}

  php-debug:
    image: ghcr.io/cors-gmbh/pimcore-docker/php-fpm-debug:8.3-alpine3.21-7.0-LATEST
    command: 'php-fpm'
    entrypoint: xdebug-entrypoint
    container_name: php-debug-cors-adminer
    depends_on:
      - db
    volumes:
      - ./:/var/www/html:cached
      - ./.docker/php.ini:/usr/local/etc/php/conf.d/docker-php-ext-additional.ini:ro
    networks:
      - cors_dev
    environment:
      - PHP_IDE_CONFIG=serverName=localhost
      - COMPOSER_AUTH=${COMPOSER_AUTH:-}

volumes:
  adminer-database:
